Add kernel command line argument documentation
runtimejs/runtime-cli pull request #6
Opened 2016-10-29 16:22 UTC by aafrey

2016-11-01 15:50 UTC, facekapow requested changes
Looks good overall, just a few minor nitpicks/issues

2016-11-01 15:50 UTC, facekapow commented on README.md
> +There is currently no officially supported process for passing environment variables into a runtime instance. There is a work around that will allow the passing of Kernel Command Line arguments inste
Probably a good idea to add a link to the issue on the main repo (https://github.com/runtimejs/runtime/issues/134) here (e.g. "While there is a \[proposal](link-here) to add this feature, there is currently no officially...").

2016-11-01 15:50 UTC, facekapow commented on README.md
> +arrayOfArguments[i]; // where i is the index of your argument inthe array
`inthe` -> `in the`

2016-11-01 15:50 UTC, facekapow commented on README.md
> +*This process is subject to change
I don't know about this, it feels too... legal 😄

2016-11-01 15:50 UTC, facekapow commented on README.md
> +To access this variable in your code user the following:
`user` -> `use`

2016-11-01 17:08 UTC, aafrey commented on README.md
> +*This process is subject to change
lol OK, cool. I can make the edits. Thanks for the feedback

2016-11-02 22:48 UTC, facekapow requested changes
2 little things

2016-11-02 22:48 UTC, facekapow commented on README.md
>  ### Environment Variables*
Remove `*`?

2016-11-02 22:48 UTC, facekapow commented on README.md
> +While there is a [proposal](runtimejs/runtime/issues/134) to add envirionment variables from the command line, there is currently no officially supported process for passing them into a runtime insta
Gotta use the full URL (`https://github.com/runtimejs/runtime/issues/134`) instead; I tried following the link from your version of the readme and it gave me a 404.

2016-11-02 23:25 UTC, facekapow approved these changes

2016-11-06 17:06 UTC, iefserge commented
👍

2016-11-06 17:07 UTC, merged